{
 "title": "Solar Gotha",
 "time": { "from": "now-16h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Momentanleistung und Ladestand",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Panels",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "victron_hq2238gypf6_panel_power"
      }
     ]
    },
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hm800_power" }
     ]
    },
    {
     "alias": "Batterie",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "pylontech_us5000_01_state_of_charge_soc"
      }
     ]
    }
   ]
  },
  {
   "title": "Batterie Strom",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "A",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "pylontech_us5000_01_battery_current"
      }
     ]
    }
   ]
  },
  {
   "title": "Tageserträge (90 Tage)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Tagesertrag Inverter",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") - min(\"value\") FROM \"kWh\" WHERE (\"entity_id\"::tag = 'hm800_yieldtotal') AND $timeFilter GROUP BY time(1d) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "hm800_yieldtotal" }
     ]
    }
   ]
  },
  {
   "title": "Tagesertrag",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Panels",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "victron_hq2238gypf6_panel_yield_today"
      }
     ]
    },
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Wh",
     "query": "SELECT mean(\"value\")  / 1000 FROM \"Wh\" WHERE (\"entity_id\" = 'hm800_yieldday') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hm800_yieldday" }
     ]
    },
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Leistung HM800",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hm800_power" }
     ]
    },
    {
     "alias": "Sonne",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "units",
     "query": "SELECT mean(\"elevation\") FROM \"units\" WHERE (\"entity_id\" = 'sun') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "elevation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "sun" }
     ]
    },
    {
     "alias": "Zaehler",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hichi_gth_sml_power_curr" }
     ]
    },
    {
     "alias": "Inverter Limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "hm800_limit_nonpersistent_absolute"
      }
     ]
    },
    {
     "alias": "Panels",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "victron_hq2238gypf6_panel_power"
      }
     ]
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Batteriestrom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "A",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "pylontech_us5000_01_battery_current"
      }
     ]
    },
    {
     "alias": "Ladestand",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "pylontech_us5000_01_state_of_charge_soc"
      }
     ]
    }
   ]
  },
  {
   "title": "Gesamtertrag (Inverter)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hm800_yieldtotal" }
     ]
    }
   ]
  },
  {
   "title": "Zählerwerte (90 Tage)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Tagesverbrauch",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT max(\"value\")-min(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'hichi_gth_sml_total_in') AND $timeFilter GROUP BY time(1d) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hichi_gth_sml_total_in" }
     ]
    },
    {
     "alias": "Tageseinspeisung",
     "query": "SELECT max(\"value\") * 1000 - min(\"value\") * 1000 FROM \"kWh\" WHERE (\"entity_id\" = 'hichi_gth_sml_total_out') AND $timeFilter GROUP BY time(1d) fill(0)"
    }
   ]
  },
  {
   "title": "Zählerstand Verbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hichi_gth_sml_total_in" }
     ]
    }
   ]
  },
  {
   "title": "Gesamtertrag (MPPT)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "victron_hq2238gypf6_panel_yield_total"
      }
     ]
    }
   ]
  },
  {
   "title": "Zählerstand Einspeisung",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hichi_gth_sml_total_out" }
     ]
    }
   ]
  },
  {
   "title": "Leistung HM800 (7 Tage)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hm800_power" }
     ]
    },
    {
     "alias": "Sonne",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "units",
     "query": "SELECT mean(\"elevation\") FROM \"units\" WHERE (\"entity_id\" = 'sun') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "elevation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "sun" }
     ]
    },
    {
     "alias": "Zaehler",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hichi_gth_sml_power_curr" }
     ]
    },
    {
     "alias": "Panels",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "victron_hq2238gypf6_panel_power"
      }
     ]
    }
   ]
  }
 ]
}